### ISSUE TITLE
Issue with checking against current user

### ISSUE THREAD

**Issue by monbro** [aumel/meteor-security-authorization#5]
We experienced some issue when a security check was done against the user which was set by `SecurityAuthorization.setAuthenticatedUser(user);` - if two users where logged in, it happended that the userA was used for a check for userB somehow. Unfortunately I can't say 100% percent it is a fault of the package or our way when and how we used `SecurityAuthorization.setAuthenticatedUser(user);`.

Actually we were setting `SecurityAuthorization.setAuthenticatedUser(user);` in `Accounts.onLogin(function(options) { ... });`

We solved the issue by changing adding a method called 'isGrantedFor()' which required the user object to be passed as a parameter. So the user, the required action and the item itself are always passed to the security voter. If it makes sense I will try to make a pull request somewhen for that.

**Comment by aumel** [comment]
Do you use the built-in account package of Meteor to log in your users ?

If yes, it's not required to set the authenticated user with `SecurityAuthorization.setAuthenticatedUser(user)` because it's done automatically by the package. It retrieves itself the user with  `Meteor.user()` in the `AuthorizationChecker`.  Try without `SecurityAuthorization.setAuthenticatedUser(user)` and tell me if you have again a problem...

If you don't use the built-in account package of Meteor, call `SecurityAuthorization.setAuthenticatedUser(user)` in a method call and tell me if it solves your problem...

Example:

``` js
Meteor.methods({
    isGrantedViewBlog: function (blog, user) {

      SecurityAuthorization.setAuthenticatedUser(user);

      return SecurityAuthorization.isGranted(['view'], blog);
    }

  });
```

**Comment by aumel** [comment]
I found the origin of the problem. 

There is only one instance of the object `SecurityAuthorization` for the app. So, the authenticated user from `SecurityAuthorization.setAuthenticatedUser(user)` is 'shared’ if we don’t set it again before calling `isGranted` function. That’s why in your example, sometimes there is a check of permission on the user A instead of the user B.

The solution is always to set the authenticated user before calling isGranted function. But it’s a little ugly :( 

So, I will fix the problem with new version of the package 2.0.0

`isGranted` function will accept the user as optional parameter when we don’t use the built-in account package of Meteor. I will remove the `SecurityAuthorization.setAuthenticatedUser`.

**Comment by monbro** [comment]
perfect, thats how I solved it as well with a patch.
